name: JuNest Builder
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "30 23 * * 0-6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo apt update
        chmod a+x ./junest-updater.sh
        ./junest-updater.sh
        if ! test -f ./.junest/usr/bin/yay; then exit; fi
        rm -R -f ./*.tar.gz
        tar -czvf junest-x86_64.tar.gz -C ./.junest/ .
        mkdir dist
        mv *tar.gz dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: junest-x86_64.tar.gz
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: junest-x86_64.tar.gz

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              junest-x86_64.tar.gz
            repo_token: ${{ secrets.GITHUB_TOKEN }}

